# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9b7ac7e0589509ed98b030a781136cd7c09c0557aa595be067630283c5a2f8acc04b050ddd57f57eb9154c5827914e045ec099a85908f0eb39a15db683675d1

test:
  secret_key_base: 85f050cc7b79cbcfdb6f7e7eb430044439b6edd242225e81b1c7303d44628a3846475739d05dec050ed85adf1b8c12b3390e77f3df4d142c2fb7c6ec8301f06d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
